---
defaults: &defaults
  working_directory: ~/cli
  docker:
    - image: node:8

version: 2

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: ls
      - run: node -v
      - run: echo "build"
  test:
    <<: *defaults
    steps:
      - run: ls
      - run: echo "test"
  release_win_x32:
    <<: *defaults
    steps:
      - checkout
      - run: echo "release win 32"
  release_win_x64:
    <<: *defaults
    steps:
      - checkout
      - run: echo "release win 64"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build
      # - release_win_x64:
      #   requires:
      #     - build
      # - release_win_x32:
      #   requires:
      #     - build
