---
defaults: &defaults
  docker:
    - image: node:8

version: 2

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: pwd
      - run: ls
      - run: node -v
      - run: echo "build" > build
  test:
    <<: *defaults
    steps:
      - run: ls
      - run: cat build
  release_win_x32:
    <<: *defaults
    steps:
      - run: cat windows_x32 > assets/windows_x32
# release_win_x64:
#   <<: *defaults
#   steps:
#     - run: echo "release win 64"

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - test:
        requires:
          - build
# - release_win_x32:
#   requires:
#     - test
#     - build
# - release_win_x64:
#   requires:
#     - build
