---
defaults: &defaults
  docker:
    - image: node:8

version: 2

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: pwd
      - run: ls
      - run: node -v
      - run: mkdir workspace
      - run: node -p "require('./package.json').version" > workspace/build
      - persist_to_workspace:
          root: workspace
          paths:
            - build
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: workspace
      - run: ls
      - run: cat workspace/build
  release_win_x32:
    <<: *defaults
    steps:
      - attach_workspace:
          at: workspace
      - run: ls
      - run: mkdir assets
      - run: cp workspace/build assets/windows_x32
      - store_artifacts:
          path: assets
          destination: windows_x32
# release_win_x64:
#   <<: *defaults
#   steps:
#     - run: echo "release win 64"

workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          filters:
            tags:
              only: /.*/
          requires:
            - build
      - release_win_x32:
          filters:
            tags:
              only: /.*/
          requires:
            - test
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
# - release_win_x64:
#   requires:
#     - build
